#!/bin/sh

if [ "$#" -ne 2 ]; then
  printf 'Usage: git-migrate remote1 remote2\n  Migrate all of remote1 to remote2'
  exit 1
fi

if [ -z $(git remote | grep "^${1}$") ]; then
  echo "Remote '${1}' does not exist!"
  exit 2
fi

if [ -z $(git remote | grep "^${2}$") ]; then
  echo "Remote '${2}' does not exist!"
  exit 3
fi

git fetch "${1}"
if [ $? -ne 0  ]; then
  exit 1
fi

git checkout master
if [ $? -ne 0  ]; then
  exit 1
fi

git merge "${1}"/master
if [ $? -ne 0  ]; then
  exit 1
fi

BRANCHES=$(git branch -r | grep "${1}")
for b in $BRANCHES; do
  echo "$b"
  branch=$(echo "$b" | sed -e "s/${1}\///")
  if [ "$branch" = 'master' ]; then
    continue;
  fi
  echo "fetching '$branch' ..."
  git fetch "${1}" "$branch":"$branch"
  if [ $? -ne 0  ]; then
    exit 1
  fi
done

git push --all "${2}"
git push --tags "${2}"
