set -g mouse on
set -s set-clipboard on
set -g allow-passthrough on
set -s copy-command 'xsel -i -b'
set -g default-terminal "tmux-256color"
set -g terminal-features ",*:clipboard,*:RGB"
set -g terminal-overrides ",*:Tc"
set -g pane-border-lines "single"
set -g pane-border-style "fg=colour246,bg=default"
set -g pane-active-border-style "fg=brightred,bold,bg=default"
set -g escape-time 50
set -g display-panes-time 2000
set -g focus-events on

bind-key -n c-g send-prefix
bind-key -n c-t send-keys c-g
