---
kind: pipeline
type: kubernetes
name: default

node:
  cluster: aliyun-k0s
  environment: cloud

node_selector:
  k8s.yusiwen.cn/role: ci-runner

steps:
  - name: sync-install-script
    image: yusiwen/repo-sync:1.1 
    pull: if-not-exists
    environment:
      MINIO_ENDPOINT: https://share.yusiwen.cn
      MINIO_ACCESS_KEY:
        from_secret: minio-access-key
      MINIO_SECRET_KEY:
        from_secret: minio-secret-key
      SYNC_LOCAL_PATH: install.sh
      SYNC_REMOTE_PATH: public/install.sh
    when:
      branch:
        - master
  
  - name: notification
    image: yusiwen/gotify-notifier:1.0.1
    environment:
      GOTIFY_URL: https://push.yusiwen.cn
      GOTIFY_TOKEN:
        from_secret: gotify-token
    when:
      status:
        - failure
        - success