#!/bin/sh
#
# ~/.xinitrc
# is a symbolic link to ~/myConfigs/xinitrc
#
# Executed by startx (run your window manager from here)

if [ -d /etc/X11/xinit/xinitrc.d ]; then
  for f in /etc/X11/xinit/xinitrc.d/*; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi

#xrdb -load "${HOME}/.Xresources"
# setxkbmap -layout latam

#gnome-settings-daemon &
#/usr/lib/policykit-1-gnome/polkit-gnome-authentication-agent-1 &

# Start GNOME Keyring
#eval $(/usr/bin/gnome-keyring-daemon --start --components=gpg,pkcs11,secrets,ssh) 
#export SSH_AUTH_SOCK
#export GPG_AGENT_INFO
#export GNOME_KEYRING_CONTROL
#export GNOME_KEYRING_PID

exec /usr/bin/i3 -V > ~/.i3/i3-$(date +'%F-%k-%M-%S').log 2>&1
