#!/usr/bin/env bash
# ~/.bashrc: executed by bash(1) for non-login shells.
# see /usr/share/doc/bash/examples/startup-files (in the package bash-doc)
# for examples

# If not running interactively, don't do anything
case $- in
    *i*) ;;
      *) return;;
esac

# don't put duplicate lines or lines starting with space in the history.
# See bash(1) for more options
HISTCONTROL=ignoreboth

# append to the history file, don't overwrite it
shopt -s histappend

# for setting history length see HISTSIZE and HISTFILESIZE in bash(1)
HISTSIZE=1000
HISTFILESIZE=2000

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# If set, the pattern "**" used in a pathname expansion context will
# match all files and zero or more directories and subdirectories.
#shopt -s globstar

# make less more friendly for non-text input files, see lesspipe(1)
[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"

load_my_scripts() {
    if [ -d "$HOME"/git/myConfigs/shell/scripts ]; then
        # shellcheck source=/dev/null
        source "$HOME/myConfigs/shell/scripts/00-environment.script"
        # shellcheck source=/dev/null
        source "$HOME/myConfigs/shell/scripts/01-colors.script"
        # shellcheck source=/dev/null
        source "$HOME/myConfigs/shell/scripts/02-functions.script"
        # shellcheck source=/dev/null
        source "$HOME/myConfigs/shell/scripts/03-programs.script"
        # shellcheck source=/dev/null
        source "$HOME/myConfigs/shell/scripts/06-aliases.script"
        # shellcheck source=/dev/null
        source "$HOME/myConfigs/shell/scripts/99-customize.script"
    fi
}

load_my_scripts

# shellcheck source=/dev/null
[ -f ~/.fzf.bash ] && source "$HOME/.fzf.bash"

if check_command zoxide; then
    eval "$(zoxide init bash)"
fi

export PS1="\[\e[32m\]\u@\h \[\e[37m\]\W \[\e[32m\]$> \[\e[37m\]"

#THIS MUST BE AT THE END OF THE FILE FOR SDKMAN TO WORK!!!
export SDKMAN_DIR="$HOME/.sdkman"
# shellcheck source=/dev/null
[[ -s "$HOME/.sdkman/bin/sdkman-init.sh" ]] && source "$HOME/.sdkman/bin/sdkman-init.sh"
check_command mc && complete -C "$(which mc)" mc
check_command aliyun && complete -C "$(which aliyun)" aliyun
