#!/usr/bin/env bash

load_my_scripts() {
  if [ -d "$HOME"/git/myConfigs/shell/scripts ]; then
    # shellcheck source=/dev/null
    source "$HOME/myConfigs/shell/scripts/00-environment.script"
    # shellcheck source=/dev/null
    source "$HOME/myConfigs/shell/scripts/01-colors.script"
    # shellcheck source=/dev/null
    source "$HOME/myConfigs/shell/scripts/02-functions.script"
    # shellcheck source=/dev/null
    source "$HOME/myConfigs/shell/scripts/03-programs.script"
    # shellcheck source=/dev/null
    source "$HOME/myConfigs/shell/scripts/06-aliases.script"
    # shellcheck source=/dev/null
    source "$HOME/myConfigs/shell/scripts/99-customize.script"
  fi
}

load_my_scripts

# shellcheck source=/dev/null
[ -f ~/.fzf.bash ] && source "$HOME/.fzf.bash"

if check_command zoxide; then
  eval "$(zoxide init bash)"
fi

#THIS MUST BE AT THE END OF THE FILE FOR SDKMAN TO WORK!!!
export SDKMAN_DIR="$HOME/.sdkman"
# shellcheck source=/dev/null
[[ -s "$HOME/.sdkman/bin/sdkman-init.sh" ]] && source "$HOME/.sdkman/bin/sdkman-init.sh"
