---
- !supmua.org,2006-10-01/Redwood/Maildir
  uri: maildir:/home/yusiwen/.mail/gmail.com/archive
  usual: true
  archived: false
  sync_back: true
  id: 1
  labels: []
- !supmua.org,2006-10-01/Redwood/SentLoader {}
